changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - octocat
  categories:
    - title: 🛠 Breaking Changes
      labels:
        - breaking-change
    - title: '🚀 Features'
      labels:
        - 'feature'
        - 'enhancement'
    - title: '🐛 Bug Fixes'
      labels:
        - 'fix'
        - 'bugfix'
        - 'bug'
    - title: '📝 Documentation'
      label: 'docs'
    - title: '🧰 Maintenance'
      label: 'chore'
    - title: '⬆️ Dependencies'
      collapse-after: 3
      labels:
        - 'dependencies'
    - title: '👷 Continuous Integration'
      collapse-after: 3
      labels:
        - 'ci'
    - title: Other Changes
      labels:
        - "*"
